# ReadMe

We build the decision tree from scratch based on the algorithm Classification and Regression Tree(CART). All the functions are wrapped in one class: Decision_tree. 

In [ ]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, w_value=None, t_value=None):

In [ ]:
class Decision_tree:
    #class_or_reg attribute can either be 'calssification' or 'regression'
    #split_type attribute can either be 'gini' or 'entropy'
    def __init__(self, class_or_reg, split_type='gini', max_depth=2, min_sample_split=1):

## Input

The input of the of the tree should be two arrays, the first one containing all the features and the second one containing all the labels

## Outputs

The Decision_tree class had 9 functions, 3 of them are to be used when using the code. The first one is the 'fit' parameter that creates the decision tree but does not return any result. 
'print_tree' function return the different nodes of the tree with the corresponding splitting values and (only for leaf nodes) the label associated.
The last useful function if 'predict' which takes as input the feature for which we want to have the label and returns a series of labels, one for each element to be predicted.

## Choose the Best Split
We defined functions to calculate gini, entropy for classification, and loss for regression, which are used to decide the best splits. 

The formulas are the following:

$$Square Error = \sum_{i=1}^{n}(y_{i}-c_{i})^2$$

$$Gini = 1-\sum_{i=1}^{n}p_{i}^{2}$$

$$Entropy = \sum_{i=1}^{n}-p_{i}*log_{2}p_{i}\$$

*where n is the number of splits, c{i} is the mean of all the values in that split, p is the probability

Information Gain = Entropy Before the Split - Weighted Average Entropy After the Split
If we want larger, information gain, we just need the smaller weighted average entropy. Therefore, to make the algorithm simpler, we focus on achieving smaller square error, gini, and not use information gain.

## Build the Tree

The dataset is splitted into left and right subsets each step based on one feature value. When the value is smaller than or equal to the split point, it is assigned to left subset, otherwise, it is assigned to the right subset.

Then we loop all the features and calculate their corresponding gini, entropy or square error to decide which feature value is best for splitting. 

We build the tree recursively. At first, the current depth is set as zero and after each splitting it is increased by one. The minimun number of samples in one node is set as default to 1.

## Print the Tree

In order to provide a visual representation of the tree to understand the splits better, we've implemented a function to visualize the tree named 'print_tree'

## Import 

In [1]:
#import standard packages
import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

In [2]:
#import decision tree
import Decision_Tree as dt_scratch

## Classification

In [3]:
#for classification
x, y = make_moons(100) 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [4]:
dt = dt_scratch.Decision_tree(class_or_reg='classification', split_type='entropy', max_depth=2)
dt.fit(x_train, y_train)
dt.print_tree()
dt.predict(x_test)

feature_1 <= -0.04553
   left: [1.]
   right: feature_1 <= 0.5
     left: feature_0 <= -0.87132
         left: [0.]
         right: [1.]
     right: [0.]


[array([0.]),
 array([0.]),
 array([0.]),
 array([1.]),
 array([1.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([0.]),
 array([1.]),
 array([1.]),
 array([0.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([1.])]

## Regression

In [24]:
#for regression
N = 100
X = np.linspace(-1, 1, N)
Y = X**2 + np.random.normal(0, 0.07, N)
X = X.reshape(-1, 1)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [26]:
dt2 = dt_scratch.Decision_tree(class_or_reg='regression', max_depth=9)
dt2.fit(X_train, Y_train)
dt2.print_tree()
dt2.predict(X_test)

feature_0 <= -0.65657
   left: feature_0 <= -0.81818
     left: feature_0 <= -0.93939
         left: feature_0 <= -1.0
                 left: [1.03261546]
                 right: [0.89568674]
         right: feature_0 <= -0.91919
                 left: [0.85663792]
                 right: feature_0 <= -0.87879
                                 left: [0.77259058]
                                 right: [0.81729987]
     right: feature_0 <= -0.71717
         left: feature_0 <= -0.77778
                 left: [0.73045384]
                 right: [0.63946665]
         right: [0.48547129]
   right: feature_0 <= 0.65657
     left: feature_0 <= -0.43434
         left: feature_0 <= -0.59596
                 left: feature_0 <= -0.63636
                                 left: [0.48123234]
                                 right: [0.34453883]
                 right: feature_0 <= -0.53535
                                 left: [0.3188669]
                                 right: feature_0 <= -0.45455


/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


[array([0.21602239]),
 array([0.63036618]),
 array([0.89568674]),
 array([0.0158136]),
 array([0.26188254]),
 array([0.79979401]),
 array([0.48547129]),
 array([0.26188254]),
 array([0.0158136]),
 array([0.88151784]),
 array([0.0158136]),
 array([0.79979401]),
 array([0.28334019]),
 array([0.63946665]),
 array([0.81729987]),
 array([0.16569719]),
 array([0.3188669]),
 array([0.21602239]),
 array([0.11333386]),
 array([0.81729987])]